#!/usr/bin/env bash
# Install HAproxy version 2.4 on your lb-01 (Load balancer) server
# HAproxy Requirements:
# - Configure HAproxy so that it send traffic to web-01 and web-02
# - Distribute requests using a roundrobin algorithm
# - Make sure that HAproxy can be managed via an init script
# - Make sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02
sudo apt-get update
sudo apt-get upgrade
apt-get install --no-install-recommends software-properties-common
sudo apt-get install -y haproxy

sudo service haproxy start

sudo chmod 777 /etc/haproxy/haproxy.cfg
printf %s "global
    maxconn 5000
    log 127.0.0.1 local0 notice
    user haproxy
    group haproxy

defaults
    timeout connect 5s
    timeout client 10s
    timeout server 10s
    log global
    mode http
    option httplog
    option dontlognull
    option redispatch

listen hbnb
    bind 0.0.0.0:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    stats enable
    server 4481-web-01 34.202.231.144:80 check
    server 4481-web-02 54.85.119.117:80 check
" > /etc/haproxy/haproxy.cfg
sudo chmod 644 /etc/haproxy/haproxy.cfg

sudo service haproxy restart
