#!/usr/bin/env bash
# Install HAproxy version 2.4 on your lb-01 (Load balancer) server
# HAproxy Requirements:
# - Configure HAproxy so that it send traffic to web-01 and web-02
# - Distribute requests using a roundrobin algorithm
# - Make sure that HAproxy can be managed via an init script
# - Make sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get update
sudo apt-get install -y haproxy=2.4.\*

sudo chmod 777 /etc/default/haproxy
echo "ENABLED=1" >> /etc/default/haproxy
sudo chmod 644 /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.old}
sudo touch /etc/haproxy/haproxy.cfg
sudo chmod 777 /etc/haproxy/haproxy.cfg
printf %s "global
    maxconn 5000
    log 127.0.0.1 local0 notice
    user haproxy
    group haproxy

defaults
    timeout connect 5s
    timeout client 10s
    timeout server 10s
    log global
    mode http
    option httplog
    option  dontlognull
    # in HTTP mode, option redispatch is set, HAProxy will automatic retry another backend if current one is down.
    option redispatch
    # client retries
    retries 3

listen hbnb
    bind 0.0.0.0:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    stats enable
    stats uri /haproxy?stats
    stats realm HAProxy\ Statistics
    server 4481-web-01 34.202.231.144:80 check
    server 4481-web-02 54.85.119.117:80 check
" > /etc/haproxy/haproxy.cfg
sudo chmod 644 /etc/haproxy/haproxy.cfg

sudo service haproxy start
