#!/usr/bin/env bash
# This script pings 5 times an IP address passed as an argument
arg=$1
n=${#arg}
  if [ "$n" -eq 0 ]
  then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  else
    ping -c 5 "$arg"
  fi
