#!/usr/bin/env bash
# This script gives you information about the school file
n=1
while [ $n -le 100 ];
do
  if [[ $((n % 3)) == 0 && $((n % 5)) == 0 ]]
  then
    echo "FizzBuzz"
  elif [ $((n % 3)) == 0 ]
  then
    echo "Fizz"
  elif [ $((n % 5)) == 0 ]
  then
    echo "Buzz"
  else
    echo $n
  fi
  n=$((n + 1))
done
