#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
COUNTER=0
while [ $COUNTER -lt 10 ];
do
  COUNTER=$((COUNTER + 1))
  echo "Best School"
  if [ $COUNTER -eq 9 ]
  then
    echo "Hi"
  fi
done