#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes
HOURS=0
while [ $HOURS -le 12 ];
do
  MINUTES=1
  echo "HOUR: $HOURS"
  while [ $MINUTES -le 59 ];
  do
    echo $MINUTES
    MINUTES=$((MINUTES + 1))
  done
  HOURS=$((HOURS + 1))
done