#!/usr/bin/env bash
# This script is displaying the content of the current directory in list format where only the part of the name after the first dash is displayed
LIST="$(ls -1 | cut -d '-' -f 2)"
for file in "$LIST";
do
  echo "$file"
done