#!/usr/bin/env bash
# This script is displaying the content of the current directory in list format where only the part of the name after the first dash is displayed
LIST="$(ls)"
for file in $LIST;
do
  echo "$file" | cut -d '-' -f 2
done